INSERT INTO employees (first_name, last_name, ROLE_ID, manager_id)
VALUES ("Chester", "Rimawi", 1, NULL),
	   ("Rebecca", "Schrick", 2, NULL),
	   ("Alexandria", "Cummings", 3, 1),
	   ("Harrison", "Freeman", 3, 1),
	   ("Bruce", "Wonderboy", 4, 1),
	   ("Natalie", "Miller", 4, 1),
	   ("Petro", "Rodriguez", 4, 1),
	   ("Grant", "Miller", 5, 1),
	   ("Chris", "Peralta", 6, NULL),
	   ("Federico", "Heinigh", 7, 9),
	   ("Ben", "Sobel", 7, 9),
	   ("Bianca", "Borg", 7, 9),
	   ("Anibal", "Moreno", 8, 9),
       ("Luis", "Rodriguez", 8, 9),
	   ("Quinn", "Stephenson", 8, 9),
	   ("Sean", "Addams", NULL, 1),
       ("Julian", "DuBois", 10, 16),
       ("Soren", "Pape", 10, 16),
       ("Abraham", "Villegas", 11, 16),
	   ("Peter", "Rogers", 11, 16);